version: '3.3'

services:

  postgres:
    image: postgres
    container_name: imaginamos
    restart: always
    environment:
      POSTGRES_DB: imgdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@imaginamos.com
      PGADMIN_DEFAULT_USER: root
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - postgres

